import { rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fluxOpenAPI from '../openapi/flux.openapi.json';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const docsDir = path.join(dirname, '..', 'content', 'docs');
const legacyOutputDir = path.join(docsDir, 'api-reference');
const outputFile = path.join(docsDir, 'api-reference.mdx');
const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'options', 'head', 'trace'] as const;

type HttpMethod = (typeof HTTP_METHODS)[number];
type Operation = { path: string; method: HttpMethod; title: string };

function humanizeOperationId(operationId: string): string {
  return operationId
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^\w/, (char) => char.toUpperCase());
}

function renderOperationHeading(operation: Operation): string {
  return `### ${operation.title}`;
}

function collectOperations(document: Record<string, unknown>): Operation[] {
  const paths = document.paths;
  if (!paths || typeof paths !== 'object') {
    return [];
  }

  const operations: Operation[] = [];
  for (const [routePath, routeItem] of Object.entries(paths)) {
    if (!routeItem || typeof routeItem !== 'object') {
      continue;
    }

    for (const method of HTTP_METHODS) {
      if (method in routeItem) {
        const operationObject = (routeItem as Record<string, unknown>)[method];
        const title =
          typeof operationObject === 'object' && operationObject !== null
            ? typeof (operationObject as Record<string, unknown>).summary === 'string'
              ? ((operationObject as Record<string, unknown>).summary as string)
              : typeof (operationObject as Record<string, unknown>).operationId === 'string'
                ? humanizeOperationId((operationObject as Record<string, unknown>).operationId as string)
                : routePath
            : routePath;

        operations.push({
          path: routePath,
          method,
          title,
        });
      }
    }
  }

  return operations;
}

const operations = collectOperations(fluxOpenAPI as Record<string, unknown>);
const operationSections = operations
  .map((operation) => {
    return `${renderOperationHeading(operation)}

<APIPage document={"flux"} operations={[${JSON.stringify({
      path: operation.path,
      method: operation.method,
    })}]} />`;
  })
  .join('\n\n');

const mdx = `---
title: API Reference
description: OpenAPI endpoint documentation with request and response details.
icon: FileText
---

{/* This file was generated by Fumadocs. Do not edit this file directly. Any changes should be made by running the generation command again. */}

## Endpoints

${operationSections}
`;

await rm(legacyOutputDir, { recursive: true, force: true });
await writeFile(outputFile, mdx, 'utf8');
